# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  skibidigamebookserver:
    image: skibidigamebookserver
    build:

      context: .
      dockerfile: skibidi_gamebook.Server/Dockerfile
    ports:
      - 5238:5238
